/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasidiskon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hinokaa
 */
public class AplikasiDiskonFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AplikasiDiskonFrame.class.getName());

    /**
     * Creates new form AplikasiDiskonFrame
     */
    public AplikasiDiskonFrame() {
        initComponents();
        setTitle("NokaShop Discount Calculator");
    setLocationRelativeTo(null);
    setResizable(false);
    }
private void hitungDiskon() {
    String priceText = tfHargaAwal.getText().trim();
    if (priceText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the initial price first.", "Empty Input", JOptionPane.WARNING_MESSAGE);
        return;
    }

    double price;
    try {
        priceText = priceText.replace(',', '.');
        price = Double.parseDouble(priceText);
        if (price < 0) throw new NumberFormatException();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid price. Please enter a positive number.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get discount from combo box or slider
    int percent = sliderDiskon.getValue();
    Object selected = cbPersentase.getSelectedItem();
    if (selected != null) {
        try {
            percent = Integer.parseInt(selected.toString());
        } catch (NumberFormatException ignored) {}
    }

    double discountAmount = price * percent / 100.0;

    // Coupon
    String coupon = tfKupon.getText().trim();
    int extraCoupon = 0;
    String couponNote = "";
    if (!coupon.isEmpty()) {
        switch (coupon.toUpperCase()) {
            case "SAVE10": extraCoupon = 10; couponNote = " + Coupon SAVE10 (10%)"; break;
            case "EXTRA5": extraCoupon = 5; couponNote = " + Coupon EXTRA5 (5%)"; break;
            case "WELCOME15": extraCoupon = 15; couponNote = " + Coupon WELCOME15 (15%)"; break;
            default: JOptionPane.showMessageDialog(this, "Invalid coupon code.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    double couponDiscount = price * extraCoupon / 100.0;
    double totalDiscount = discountAmount + couponDiscount;
    double finalPrice = price - totalDiscount;
    if (finalPrice < 0) finalPrice = 0;

    lblHargaAkhir.setText("Total Price: Rp " + String.format("%,.2f", finalPrice));
    lblJumlahHemat.setText("You Saved: Rp " + String.format("%,.2f", totalDiscount));

    // Add to history area
    String history = "Original Price: Rp " + String.format("%,.2f", price) +
            "\nMain Discount: " + percent + "% -> Rp " + String.format("%,.2f", discountAmount) +
            (extraCoupon > 0 ? "\nCoupon" + couponNote + " -> Rp " + String.format("%,.2f", couponDiscount) : "") +
            "\nTotal Saved: Rp " + String.format("%,.2f", totalDiscount) +
            "\nFinal Price: Rp " + String.format("%,.2f", finalPrice) + "\n---\n";
    taRiwayat.insert(history, 0);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        tfHargaAwal = new java.awt.TextField();
        cbPersentase = new javax.swing.JComboBox<>();
        lblHargaAwal = new java.awt.Label();
        lblDiskon = new java.awt.Label();
        lblKupon = new java.awt.Label();
        tfKupon = new java.awt.TextField();
        sliderDiskon = new javax.swing.JSlider();
        btnHitung = new javax.swing.JButton();
        lblHargaAkhir = new java.awt.Label();
        lblJumlahHemat = new java.awt.Label();
        taRiwayat = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Noka");

        label1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 51));
        label1.setText("Shop!");

        tfHargaAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaAwalActionPerformed(evt);
            }
        });

        cbPersentase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "10%", "15%", "20%", "25%", "30%", "40%", "50%", " " }));
        cbPersentase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPersentaseActionPerformed(evt);
            }
        });

        lblHargaAwal.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblHargaAwal.setForeground(new java.awt.Color(0, 0, 0));
        lblHargaAwal.setText("Price         :");

        lblDiskon.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblDiskon.setForeground(new java.awt.Color(0, 0, 0));
        lblDiskon.setText("Discount :");

        lblKupon.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblKupon.setForeground(new java.awt.Color(0, 0, 0));
        lblKupon.setText("Cupon      :");

        tfKupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKuponActionPerformed(evt);
            }
        });

        sliderDiskon.setForeground(new java.awt.Color(255, 153, 0));
        sliderDiskon.setMajorTickSpacing(10);
        sliderDiskon.setMaximum(50);
        sliderDiskon.setMinorTickSpacing(5);
        sliderDiskon.setPaintLabels(true);
        sliderDiskon.setPaintTicks(true);
        sliderDiskon.setValue(10);

        btnHitung.setBackground(new java.awt.Color(0, 0, 0));
        btnHitung.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 153, 0));
        btnHitung.setText("Count It!");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblHargaAkhir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblHargaAkhir.setForeground(new java.awt.Color(0, 0, 0));
        lblHargaAkhir.setText("Total Price : Rp0.00");

        lblJumlahHemat.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblJumlahHemat.setForeground(new java.awt.Color(0, 0, 0));
        lblJumlahHemat.setText("You Saved: Rp0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPersentase, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKupon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHargaAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(lblJumlahHemat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(131, 131, 131))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHitung)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHargaAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tfHargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cbPersentase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tfKupon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblKupon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(sliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHargaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJumlahHemat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        lblDiskon.getAccessibleContext().setAccessibleName("Discount :");

        pack();
    }// </editor-fold>                        

    private void tfHargaAwalActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void cbPersentaseActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void tfKuponActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {                                          
    hitungDiskon();    // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AplikasiDiskonFrame().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbPersentase;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label lblDiskon;
    private java.awt.Label lblHargaAkhir;
    private java.awt.Label lblHargaAwal;
    private java.awt.Label lblJumlahHemat;
    private java.awt.Label lblKupon;
    private javax.swing.JSlider sliderDiskon;
    private java.awt.TextArea taRiwayat;
    private java.awt.TextField tfHargaAwal;
    private java.awt.TextField tfKupon;
    // End of variables declaration                   
}
